# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 429f87857a21687d6b119012c40c5542982114f473903d07436e03f5190a5b9b7195d95682cf00a56c37da088f3bbc973f40d3033c1d95a0aa795a3ba53f7cbb

test:
  secret_key_base: 615b2b4299796e635acd2d6cf6fbdb92c76533c02763281400c193b70cc57bb2e996a940559689b6de2e679b354321a8fb2ff3aba56609c50f38a6132f65dd91

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
